[package]
name = "rs_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
directories = "6.0.0"
colored = "3.0.0"
